version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: iamok-health-app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: iamok
      POSTGRES_PASSWORD: iamok123
      POSTGRES_DB: iam_ok_health_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: iamok-health-app-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  wiremock:
    image: wiremock/wiremock:3.3.1
    container_name: iamok-health-app-wiremock
    ports:
      - "8089:8080"
    environment:
      - WIREMOCK_OPTIONS=--global-response-templating
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    restart: unless-stopped

volumes:
  pgdata:
