spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_ok_health_db
    username: iamok
    password: iamok123

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: iam_ok_health

  flyway:
    enabled: true
    schemas: iam_ok_health
    default-schema: iam_ok_health
    baseline-on-migrate: true
    locations: classpath:db/migration
